---
- name: Install R1soft on any OS 
  hosts: all
  tasks:
    - name: Create repo on RedHat Family
      when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" ) or
            ( ansible_distribution == "Fedora" )
      copy:
        src: /root/r1soft/r1soft.repo
        dest: /etc/yum.repos.d/r1soft.repo

    - name: Install r1soft agent
      when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" ) or
            ( ansible_distribution == "Fedora" ) 
      package:
        name: serverbackup-enterprise-agent
      ignore_errors: true
                                            
    - name: Start r1soft agent
      when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" ) or
            ( ansible_distribution == "Fedora" ) 
      systemd:
        name: sbm-agent
        state: started

 
# Install r1soft on Debian Family
 
        
    - name: Add repo source list
      when: ( ansible_distribution == "Debian") or
            ( ansible_distribution == "Ubuntu")
      shell: "echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list" 

    - name: Download package
      when: ( ansible_distribution == "Debian") or
            ( ansible_distribution == "Ubuntu")
      get_url:
        url: http://repo.r1soft.com/r1soft.asc
        dest: /tmp/r1soft.asc
  
    - name: Get the Key
      when: ( ansible_distribution == "Debian") or
            ( ansible_distribution == "Ubuntu")
      shell: apt-key add /tmp/r1soft.asc
      
    - name: Update packages
      when: ( ansible_distribution == "Debian") or
            ( ansible_distribution == "Ubuntu")
      apt:
        update_cache: yes

    - name: Install r1soft agent
      when: ( ansible_distribution == "Ubuntu") or
            ( ansible_distribution == "Debian")
      package:
        name: serverbackup-enterprise-agent
        state: present
    
    - name: Start r1soft agent
      when: ( ansible_distribution == "Ubuntu") or
            ( ansible_distribution == "Debian")
      service:
        name: cdp-agent
        state: restarted

    - name: Get Key from Backup
      when: ( ansible_distribution == "CentOS") or
            ( ansible_distribution == "Fedora") or
            ( ansible_distribution == "Debian") or
            ( ansible_distribution == "Ubuntu")
      shell: "r1soft-setup --get-key http://backup.devopnet.com"   
