---
- name: Create EC2
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Creat EC2 instances
      ec2: 
        key_name: dynamic-ansible
        instance_type: t2.micro
        image: ami-09693313102a30b2c 
        assign_public_ip: yes
        region: eu-west-1
        vpc_subnet_id: subnet-68583d0e
