apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nexus-volume
  labels:
    app: nexus 
spec: 
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/volume-local"
