apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: tools
spec:
  selector:
    app: nexus
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: docker-repo
