apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    name: jenkins
  name: jenkins
  namespace: tools
spec:
  ports:
  - nodePort: 30618
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
    name: jenkins
  type: LoadBalancer
